---
include:
# Left Shields / Default - with AML
  - board: seeeduino_xiao_ble
    shield: SAA_L_Base SAA_L_TB rgbled_adapter nice_oled
    snippet: Default zmk-usb-logging studio-rpc-usb-uart
    artifact-name: SAA_L_MODULE_TB

  - board: seeeduino_xiao_ble
    shield: SAA_L_Base SAA_L_JOY rgbled_adapter nice_oled
    snippet: Default zmk-usb-logging studio-rpc-usb-uart
    artifact-name: SAA_L_MODULE_JOY

  - board: seeeduino_xiao_ble
    shield: SAA_L_Base SAA_L_ENC rgbled_adapter nice_oled
    snippet: Default zmk-usb-logging studio-rpc-usb-uart
    artifact-name: SAA_L_MODULE_ENC

  - board: seeeduino_xiao_ble
    shield: SAA_L_Base SAA_L_TPD rgbled_adapter nice_oled
    snippet: Default zmk-usb-logging studio-rpc-usb-uart
    artifact-name: SAA_L_MODULE_TPD

  - board: seeeduino_xiao_ble
    shield: SAA_L_Base SAA_L_KEY rgbled_adapter nice_oled
    snippet: Default zmk-usb-logging studio-rpc-usb-uart
    artifact-name: SAA_L_MODULE_KEY

# Right Shields
  - board: seeeduino_xiao_ble
    shield: SAA_R_Base SAA_R_TB rgbled_adapter nice_oled
    snippet: zmk-usb-logging studio-rpc-usb-uart
    artifact-name: SAA_R_MODULE_TB
    
  - board: seeeduino_xiao_ble
    shield: SAA_R_Base SAA_R_JOY rgbled_adapter nice_oled
    snippet: zmk-usb-logging studio-rpc-usb-uart
    artifact-name: SAA_R_MODULE_JOY

  - board: seeeduino_xiao_ble
    shield: SAA_R_Base SAA_R_ENC rgbled_adapter nice_oled
    snippet: zmk-usb-logging studio-rpc-usb-uart
    artifact-name: SAA_R_MODULE_ENC

  - board: seeeduino_xiao_ble
    shield: SAA_R_Base SAA_R_TPD rgbled_adapter nice_oled
    snippet: zmk-usb-logging studio-rpc-usb-uart
    artifact-name: SAA_R_MODULE_TPD

  - board: seeeduino_xiao_ble
    shield: SAA_R_Base SAA_R_KEY rgbled_adapter nice_oled
    snippet: zmk-usb-logging studio-rpc-usb-uart
    artifact-name: SAA_R_MODULE_KEY

# Settings Reset
  - board: seeeduino_xiao_ble
    shield: settings_reset

