---
include:
# Unified firmware
  - board: seeeduino_xiao_ble
    shield: SAA_L_Base rgbled_adapter nice_oled
    snippet: Central ModuleMux IQS zmk-usb-logging studio-rpc-usb-uart
    artifact-name: SAA_L_UNIFIED

  - board: seeeduino_xiao_ble
    shield: SAA_R_Base rgbled_adapter nice_oled
    snippet: Peripheral ModuleMux IQS zmk-usb-logging studio-rpc-usb-uart
    artifact-name: SAA_R_UNIFIED

# Settings Reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
