# Analog input settings for JOY candidates
CONFIG_ADC=y
CONFIG_ADC_ASYNC=y

# DYA Analog Input Module settings
CONFIG_DYA_ANALOG_INPUT=y

# PMW3610 trackball settings for TB candidates
CONFIG_SPI=y
CONFIG_PMW3610=y
CONFIG_PMW3610_SWAP_XY=n
CONFIG_PMW3610_INVERT_X=n
CONFIG_PMW3610_INVERT_Y=y
CONFIG_PMW3610_SMART_ALGORITHM=y
CONFIG_PMW3610_REPORT_INTERVAL_MIN=14

# Cirque touchpad settings for TPD candidates
CONFIG_I2C_GPIO=y
CONFIG_INPUT_PINNACLE=y
CONFIG_ZMK_INPUT_PINNACLE_IDLE_SLEEPER=n
