name: Draw ZMK keymaps
on:
  workflow_dispatch:
  push:
    paths:
      - "config/*.keymap"
      - "config/*.json"
      - "boards/**/*.dtsi"
      - "boards/**/*.overlay"
      - "snippets/**/*.overlay"
      - "keymap-drawer/config.yaml"
      - ".github/workflows/draw-keymap.yml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      commit_message: "[Draw] ${{ github.event.head_commit.message }}"
      amend_commit: false
      install_branch: "main"
      keymap_patterns: "config/*.keymap"
      json_path: "config"
      config_path: keymap-drawer/config.yaml
      output_folder: keymap-drawer
      destination: "both"
      parse_args: ""  # map of extra args to pass to `keymap parse`, e.g. "corne:'-l Def Lwr Rse' cradio:''"
      draw_args: "SAA:'-j config/SAA.json'"

  draw-keymap-svg:
    needs: draw
    uses: te9no/zmk-workspace/.github/workflows/draw-keymap-svg.yml@main
    permissions:
      contents: write
    with:
      commit_message: "[Draw keymap-svg] ${{ github.event.head_commit.message || 'manual run' }}"
      amend_commit: false
      keymap_patterns: "config/*.keymap"
      output_folder: "keymap-svg"
      destination: "both"
      artifact_name: "keymap-svg"
